src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.js

Keep `GmailThreadView.prototype.addNoticeBar` from throwing.

fix: Add alternate selector for subject container

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.js
src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.js

add `.PeIF1d` selector to monitor thread changes in split mode
fix for https://github.com/InboxSDK/InboxSDK/issues/789

fix: add support for new thread selectors

---

gulpfile.babel.ts
packages/core/package.json
src/inboxsdk-js/loading/platform-implementation-loader.ts
src/platform-implementation-js/lib/inject-script-EMBEDDED.ts
src/platform-implementation-js/platform-implementation.js

This PR starts including sourcemaps in the MV3 npm release, and also makes sourcemaps be loaded when using the MV2 remote-loaded release.

Public sourcemaps

---

src/common/log-error.ts
src/platform-implementation-js/lib/logger.ts

We're changing some of our event and error tracking infrastructure and updating the URLs the InboxSDK hits for these.

Update event and error tracking URLs

---

src/injected-js/gmail/setup-gmonkey-handler.ts

Prevent `TypeError: window.gmonkey.v2.getCurrentThread is not a function.` flavor errors in the SDK.

fix: optional chain for all of gmonkey thread pulling

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.js

Gmail encodes emoji in a way that allows it to keep emoji on brand.
```html
```
This PR extracts `data-emoji` attributes if present to allow them to be reflected in `ThreadView.prototype.getSubject`.

Fix: parse emoji in thread view subject

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.js

Hello,
As suggested by @aleemstreak in https://github.com/InboxSDK/InboxSDK/issues/842#issuecomment-1430076502 , I made a PR to fix #842.
The problem was well described in the bug issue and the JS error is straightforward. The code was trying to access a variable before the initialization. I couldn't figure out _why_ this happened only now, but the issue was a name shadowing that should have worked but somehow in the minified version it confused the name.
The fix is simple, we just use another variable name to avoid the variable shadowing. I could reproduce the issue locally using the `main` branch and changing the name fixed it.

Fix ComposeView.attachFiles() by avoiding variable shadowing

---

.circleci/config.yml
.eslintignore
.eslintrc.js
.flowconfig
gulpfile.babel.ts
package.json
packages/core/.npmignore
packages/core/package.json
tsconfig.declarations.json
tsconfig.json
yarn.lock

A subset of the changes in #837 related to outputting JS stripped of TS and Flow cruft.

chore: split type/src output changes from former #837

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-app-menu-item-view.ts

When switching between default and active menu items in the experimental app menu work, we would flash as the browser redownloaded each image. This change exploits the fact that after #836, we only support [browsers that support preload](https://caniuse.com/link-rel-preload).

fix: prevent FOUC when (de-)?activating menu items

---

package.json
packages/core/package.json
src/platform-implementation-js/dom-driver/gmail/gmail-driver/add-app-menu-item.ts
src/platform-implementation-js/dom-driver/gmail/gmail-driver/track-gmail-styles.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-app-menu-item-view.ts
src/platform-implementation-js/namespaces/app-menu.ts
src/platform-implementation-js/views/app-menu-item-view.ts
src/platform-implementation-js/views/collapsible-panel-view.ts
yarn.lock

When swapping from light <-> dark themes within gmail, update icons in the app menu panel accordingly.

feat: update app menu icons on theme swap

---

src/platform-implementation-js/namespaces/app-menu.ts
src/platform-implementation-js/style/gmail.css
src/platform-implementation-js/views/collapsible-panel-view.ts

Incorporates part of the relaxing of required types around `PanelDescriptor.primaryButton.iconUrl` like #857.

feat: add dark theme api support for panel

---

src/platform-implementation-js/views/collapsible-panel-view.ts

Uses the same preload trick from app menu items.

fix(app-menu): prevent FOUC on collapsible primary button icon

---

src/platform-implementation-js/dom-driver/gmail/gmail-element-getter.ts

And default to the app burger menu being being open, even if the selector is not found.

fix(app-menu): update selector for app burger menu collapsed

---

src/platform-implementation-js/dom-driver/gmail/gmail-element-getter.ts

Between fa70a731 and 0ab54548, we had a fallback get flipped from `true` to `false`. Update to rematch the comment with corresponding logic.

chore: remove stale comment

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.js

This PR fixes the issues where custom views don't have the proper 16px margin at the bottom of the screen like native views, causing the page to be made too tall which causes HTMLElement.scrollIntoView() calls to scroll document.body itself, which isn't normally scrollable and causes content at the top of the page to be irreversibly scrolled out of view.

Fix custom view sizing

---

src/platform-implementation-js/views/native-nav-item-view.js
src/platform-implementation-js/views/nav-item-view.js

Instead of using a `setTimeout` or a `MutationObserver`, it would be great to be notified by an event (`inserted` / `created`) when the NavItemView has been inserted in the DOM and when he is queryable with a `querySelector`.

Feature Request: Emit event when NavItemView is inserted

---

src/platform-implementation-js/dom-driver/gmail/gmail-driver/track-gmail-styles.ts

Hi,
I've recently found that the class `inboxsdk__gmail_density_compact` was always set on the body even if the actual density setting was set to "Default" or "Comfortable".
I've made the changes in the method `getDensity` to detect if the density was set to Compact or Default/Comfortable.
Sadly, they are no visual/class changes between "Default" and "Comfortable" density!
I've used the key `default` for the default density, but it can be `cozy` to keep better retro compatibility, but `default` looks more relevant with the setting's name.
Steps to reproduce:
1. Load any extension using the InboxSDK
2. In the Gmail "Quick settings" switch the density from Compact to Default, the class `inboxsdk__gmail_density_compact` will always be on the body element

fix: getDensity method

---

__tests__/inboxsdk-gmail.ts
babel.config.js
gulpfile.babel.ts
jest.config.js
src/common/version.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-app-sidebar-view/index.test.js
src/platform-implementation-js/dom-driver/gmail/views/gmail-app-sidebar-view/primary/index.js
src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-sidebar-view.js
src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-sidebar-view.test.js
src/platform-implementation-js/driver-common/sidebar/ContentPanelViewDriver.js
src/platform-implementation-js/driver-common/sidebar/constants.js.flow
src/platform-implementation-js/driver-common/sidebar/constants.ts
src/platform-implementation-js/lib/idMap.js.flow
src/platform-implementation-js/lib/idMap.ts

Prevents issues where a @inbox/core@>=1.1.0 is unable to find the Gmail sidebar after an older @inbox/core using extension loads. This issue was introduced in #881.
From @Macil:
> ContentPanelViewDriver's constructor expects an element with the classname idMap('app_sidebar_waiting_platform') to exist already. The constructor is called from the addThreadSidebarContentPanel method of GmailAppSidebarView. GmailAppSidebarView's own constructor detects whether it's the first SDK instance, and if it is, constructs GmailAppSidebarPrimary which creates the element.
> 
> So it looks like it is the issue I brought up: if a different SDK loaded first, it will create the idMap('app_sidebar_waiting_platform') element, mark itself as the primary, and then other SDK instances will expect to find an …

fix: partially bring back older idMap impl

---

packages/core/package.json
yarn.lock

`@inboxsdk/core@1.1.4` with Typescript's tsc run on it fails in outside projects. This PR adds the following dependencies for TS types.
- `live-set`
- `page-parser-tree`
- `transducers.js`

chore: add types for TS consumers

---

.browserslistrc

Safari 15 cannot handle this syntax when code is minified
```
import once from 'lodash/once';
class Hello {
world = once(() => {
return "hello world";
});
}
```
the file that fails to be executed in Safari v15 is `src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.js`
the bug was made in the https://github.com/InboxSDK/InboxSDK/pull/881

rollback browserlist to Safari v14

---

src/inboxsdk.d.ts

Takes advantage of #848 to use one consistent set of typing for `sdk.Logger`.

chore: use real Logger type instead of idealized version

---

.browserslistrc
babel.config.js

Fix for #904. Our usage of CJS inside of ESM exports seems to generate a ReferenceError with our stack in Safari 15 when coupled with a class that's being assigned to `module.exports` within a ud defn function.
Swapping our browserslist default creates quite a bit of noise in our error logging, as it changes stack trace locations and increases stack size. ~It also increases our output code size by roughly 10%.~ _edit: bundlephobia doesn't rounds the two output sizes together, but we're in the ~1% range minified._
~Longer term, I'd like to remove the remainder of ud in its entirety as it doesn't work with TS and is thus blocking moving off flow.~ _See #910._

fix: reapply Safari 15 min

---

examples/app-menu/content.js
src/platform-implementation-js/dom-driver/gmail/gmail-element-getter.ts
src/platform-implementation-js/namespaces/app-menu.ts
src/platform-implementation-js/views/collapsible-panel-view.ts

Allows timing events that require measuring around the width transition in collapsible panels.

feat: add collapseToggled event to AppMenu

---

.gitignore
gulpfile.babel.ts
package.json
yarn.lock

If you're not using a bundler, using `inboxsdk.min.js` instead of `inboxsdk.js` should mirror the old behavior.
Related to debugging #933.
Without #938, note that with this change the minified `inboxsdk.min.js` is using terser@5.18.2, while the remote loaded SDK is using terser@5.16.

chore: turn off minification for npm published builds by default

---

babel.config.js
yarn.lock

Bumps to terser@5.18.2 with `yarn up terser`. Should prevent an issue in #934 where we use different versions of terser between remote loaded code and the minified npm build.
terser@5.17.6 includes "fixes to mozilla AST's input and output, for class properties, private properties and static blocks". 
https://github.com/terser/terser/blob/master/CHANGELOG.md#v5176
This should resolve the discrepancy we saw between our downstream project which still has private field transforms enabled and uses currently uses a number of terser versions with `terser@5.16.8` being the max.
Related to #906.

chore: reenable class field transforms

---

gulpfile.babel.ts
package.json
src/platform-implementation-js/lib/inject-script-EMBEDDED.ts
yarn.lock

chore: drop deprecated raw-loader in favor of asset-modules

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/manage-button-grouping.ts
src/platform-implementation-js/style/gmail.css

- fix: remove overflow monkey patch
- tweak grouping of custom toolbar buttons to respond to native toolbar button overflow
The overflow: visible rule the SDK's styling adds seems to break Gmail's ComposeView toolbar menu overflow detection.
Closes #931

fix: rework ComposeView overflow menu handling

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/manage-button-grouping.ts
src/platform-implementation-js/style/gmail.css

Removes additional button padding and margin around the ComposeView toolbar. @hwfwalton pointed out these styles were added a number of major Gmail changes ago.
The `.inboxsdk__compose_narrow_buttons` class made compose toolbar buttons wider. This was happening irrespective of how wide the compose view was when it was created.
There is still the bug around composes and button overflow when the client is <= 1000px wide. I believe that should be fixed with Gmail handles narrower than 1000px screens with ComposeView. For clients wider than 1000px, this patch should allow native button styles through.
At roughly 1000px wide with the [example extension found here.](https://github.com/InboxSDK/InboxSDK/blob/e957bfff657e0f7fe2fd3a2b9764738a6e1fd5cd/examples/compose-tooltip-button/content.js#L1) …

fix: stale style monkey patch in ComposeView

---

gulpfile.babel.ts
src/inboxsdk-js/loading/platform-implementation-loader.ts

Related to #950. Sentry still seems to be caching source map paths regardless of `sourceMappingURL` being set. `sourceMappingURL` being set doesn't seem to work eval. This PR swaps back to using `sourceURL` but appended by webpack on each build target.

chore: append sourceURL in lieu of sourceMappingURL

---

src/common/load-script.ts
src/inboxsdk-js/loading/platform-implementation-loader.ts

#959 successfully appended `sourceURL` but had an additional sourceURL comment added after resulting in a remotely loaded platform-implementation.js that ended with the following:
```
//# sourceURL=https://www.inboxsdk.com/build/platform-implementation.js?hash=4cefb05b726253ed68d15ba8d34e03b8
//# sourceURL=https://www.inboxsdk.com/build/platform-implementation.js
```
This change should only include the former sourceURL and not the latter.
Related to #950

chore: disable double sourceURL

---

src/inboxsdk.d.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-message-view.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-message-view/attachment-icon.ts
src/platform-implementation-js/driver-interfaces/message-view-driver.ts
src/platform-implementation-js/views/conversations/message-view.ts

This PR should be only TS type level changes. It also 
- adds narrower `getEventStream` typing for both the MessageView and its driver
- unlinks the Driver being an intersection type with the MessageView interface
Prelim for #939

chore: tie MessageView interface to MessageView and its driver

---

.stylelintrc.yaml
examples/modal-example/content.js
src/platform-implementation-js/style/gmail.css

[Using this example extension](https://github.com/InboxSDK/InboxSDK/blob/6dee33e3c9306ae00b3a959b4ea05d3a0ad474a7/examples/modal-example/content.js#L3)
Note the _X_ in the top right of the modal on the right.
Closes #903

fix(#903): use higher dpi image for close button on retina screens

---

__tests__/injected-thread-identifier.ts
examples/thread-rows/content.js
src/injected-js/gmail/thread-identifier/click-and-get-popup-url.ts
src/injected-js/gmail/thread-identifier/index.ts
src/injected-js/gmail/thread-identifier/thread-row-parser.ts
src/platform-implementation-js/dom-driver/gmail/gmail-page-communicator.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts
src/platform-implementation-js/lib/dom/custom-events.ts

Skip trying to extract metadata for ads in Gmail's Promotions tab.
The way I've checked parsing after the change was with the sample extension found here: https://github.com/InboxSDK/InboxSDK/blob/833d6b8bcca9646c36b627f67e2f73958364e3f7/examples/thread-rows/content.js.
Closes #943

fix: skip extraction of threadMetadata for Gmail Ads

---

examples/compose-tooltip-button/content.js
src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.ts

See https://github.com/InboxSDK/InboxSDK/issues/953#issuecomment-1660996299. It appears that fullscreen compose file attachment dropzones don't have a `style.height` set, and so our `bottom <= rect.bottom` check was failing.
Closes #953

fix: ComposeView.prototype.attachFiles in fullscreen mode

---

gulpfile.babel.ts
src/common/load-script.ts
src/inboxsdk-js/loading/platform-implementation-loader.ts
src/platform-implementation-js/lib/inject-script-EMBEDDED.ts

This reverts commit 78440a9bd48064e4f9d164d0a535ef7599cef5ea and e9debbf29798ef0b589affe3e780deaaa43085d1.
958d1cd (#960) was reverted in #974.

Revert "fix: caching of remote loaded SDK source maps"

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-attachment-card-view.ts

Before commit a57d655e a new BasicButtonViewController was instantiated and assigned to a variable which was never used.
I assume this was catched by ESLint and the variable assignment was removed.
Unfortunately the BasicButtonViewController was needed to make the button work.

fix: re-enable attachment card button onClick handler

---

gulpfile.babel.ts

We've used 0.7.25 as the first portion of our BUILD_VERSION triplet since 2019 -> https://github.com/InboxSDK/InboxSDK/blob/4da86a834e886efc6a651ff91f4d521fa7519427/package.json#L124
This PR uses the maintained version (currently 1.2.5) from @inboxsdk/core both in the npm version and the remote one

chore: use maintained version in BUILD_VERSION string

---

package.json
yarn.lock

This dependency hasn't been necessary since #836. Leaves one dependency using core-js@2, `order-manager`

chore: drop safari-fix-map

---

src/injected-js/gmail/thread-identifier/thread-row-parser.ts

Supports an additional ad format when identifying ads in Gmail's Promotions and Social tabs.
Tested with sample extension: https://github.com/InboxSDK/InboxSDK/tree/main/examples/thread-rows
Closes https://github.com/InboxSDK/InboxSDK/issues/1000

fix: expand isThreadRowAd selector to include a different ad format

---

examples/mole-example/manifest.json

Cherry picked from #1008 to test #970's dropping of MV2 support from npm builds.

MV3ify mole-example

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts

The tooltip was not displaying when hovering the thread row view button. Upon inspecting the Gmail DOM, it was observed that other native Gmail buttons utilize the data-tooltip attribute for tooltip text.

Added data-tooltip to Toolbar Button

---

examples/add-route-view-sections/manifest.json
examples/app-menu/manifest.json
examples/attachment-card/manifest.json
examples/browser-test/manifest.json
examples/compose-dropdown-button/manifest.json
examples/compose-stream/manifest.json
examples/compose-tooltip-button/manifest.json
examples/contact-hover-example/manifest.json
examples/custom-thread-list/manifest.json
examples/custom-view/manifest.json
examples/header-support/manifest.json
examples/hello-world/manifest.json
examples/link-popovers/manifest.json
examples/modal-example/manifest.json
examples/mole-example/manifest.json
examples/nav-menu/manifest.json
examples/open-compose/manifest.json
examples/override-edit-subject/manifest.json
examples/search-results/manifest.json
examples/search-suggestions/manifest.json
examples/search-term/manifest.json
examples/sidebar-contact-example/manifest.json
examples/sidebar-example/manifest.json
examples/thread-rows/manifest.json
examples/thread-test/manifest.json
examples/toolbar-button/manifest.json

After #970, all but two our examples no longer work. To remedy that, this PR moves over the
existing MV2 configs to be the MV3 equivalent. Among other things, it:
- adds `"scripting"` as a permission along with `"host_permissions"`
- nests `"web_accessible_resources"`
- bumps example extension versions from {0.1 => 2.0}
- removes source map files that aren't accessible in MV3
It uses the following script to port MV2 manifests to MV3.
```js
import fs from 'node:fs';
import path from 'node:path';
for (const exampleFolder of fs.readdirSync('examples')) {
const candidatePath = path.join('examples', exampleFolder, 'manifest.json');
if (!fs.existsSync(candidatePath)) {
continue;
}
let manifest = JSON.parse(
fs.readFileSync(candidatePath, {
encoding: 'utf-8',
})
);
if (manifest.manifest_version …
```

chore: move examples folder over to MV3 support

---

gulpfile.babel.ts
package.json
src/common/assert.test.ts
src/common/assert.ts
src/injected-js/gmail/thread-identifier/thread-row-parser.ts
src/injected-js/xhr-proxy-factory.test.ts
src/injected-js/xhr-proxy-factory.ts
src/platform-implementation-js/dom-driver/gmail/gmail-response-processor.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-row-list-view.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts
test/lib/mock-element-parent.ts
yarn.lock

Removes node polyfill `assert` in favor of a single function. In tests, `node:assert` is used. Where `assert.strictEqual` was used previously in browser code, `assert(Object.isEqual(...))` is now used.
Note: there are at node polyfills present within the SDK for:
- `buffer`
- `querystring-es3`
- `process`

chore: drop node polyfill 'assert'

---

src/platform-implementation-js/dom-driver/gmail/gmail-driver.ts

`title`  property was missing when passing Button descriptor to  `gmailThreadRow.addButton()`

added missing title property

---

src/injected-js/gmail/setup-gmail-interceptor.ts

Fixes "TypeError: Failed to construct 'URL': Invalid URL" errors showing up in console occasionally. These errors were not breaking any functionality; they were just caught and noisily logged.
The error was caused because I forgot that `connection.url` could be a relative URL.

Fix errors in console

---

src/platform-implementation-js/dom-driver/gmail/widgets/gmail-mole-view-driver.ts
src/platform-implementation-js/driver-common/sidebar/ContentPanelViewDriver.ts

Scavenges work around #1036 
- relax type def around ContentPanelDescriptor
- enforce private on ViewDriver fields/methods

chore: tighten mole view driver up

---

__tests__/inboxsdk-gmail.ts
src/common/ajax.ts
src/inboxsdk.d.ts
src/platform-implementation-js/dom-driver/gmail/gmail-driver.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-app-sidebar-view/index.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-app-sidebar-view/primary/index.tsx
src/platform-implementation-js/driver-common/getGmailThreadIdForRfcMessageId.ts
src/platform-implementation-js/driver-common/sidebar/ContentPanelViewDriver.ts
src/platform-implementation-js/views/content-panel-view.ts

As part of prep work for reworking mole & sidebar interactions, go through the existing sidebar interface and look for non-public usages that could be private.
- chore: true private in several @internal classes
- remove several `any`s

chore: stricter sidebar interface

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts

follow up on https://github.com/InboxSDK/InboxSDK/pull/1045, we changed how we were checking isListRoute, it turns out we had the use case we indeed are on a thread view but we render a list of the messages on the thread view, we'd still need the isListRoute to be false in this case, so adding it back and a comment for it.

Fix isListRoute check

---

package.json
src/common/rate-limit-queuer.test.ts
src/common/rate-limit.test.ts
yarn.lock

Bumping to `order-manager@1.0.3` drops our last usage of `babel-runtime`.

chore: bump order-manager to remove old babel-runtime dep

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts

check is not thread instead of finding the row list elements which could be async loaded -> tested search results example working fine

fix isListRoute for searching result page route detection

---

gulpfile.babel.ts
src/platform-implementation-js/dom-driver/gmail/gmail-driver/isIntegratedViewGmail.ts
src/platform-implementation-js/dom-driver/gmail/widgets/gmail-mole-view-driver.ts
src/platform-implementation-js/dom-driver/gmail/widgets/mole-view.module.css

1. Open Gmail Compose mole
2. Open SDK mole
3. Open Gmail Compose mole
4. Open SDK mole
Results in the following mole order, from left to right:
```
[4] [3] [2] [1]
```
1. Open Gmail Compose mole
2. Open SDK mole
3. Open Gmail Compose mole
4. Open SDK mole
Results in the following mole order, from left to right:
```
[1] [2] [3] [4]
```

fix: order SDK moles as Gmail does Composes

---

src/platform-implementation-js/dom-driver/gmail/gmail-element-getter.ts
src/platform-implementation-js/dom-driver/gmail/widgets/gmail-mole-view-driver.ts
src/platform-implementation-js/dom-driver/gmail/widgets/mole-view.module.css

When we add SDK moles to Gmail, we add them in the same element that Gmail adds ComposeViews (and if Chat is enabled, Chat moles)--the moleParent. The moleParent doesn't seem to exist by default when Gmail starts up unless:
- there's a ComposeView lingering from a previous Gmail load
- The user is on a route like MessageView where there are inline ComposeViews
The way we ensure the moleParent is present (only an issue once per page load) is by quickly opening a ComposeView and then closing it. This can be slow enough that there is a FOUC around the ComposeView showing up alongside an SDK mole.
This PR adds a class to `document.body` while we're forcing moleParent into existence to hide the FOUC. It also discards instead of just closing the temporary compose draft to handle the edge case …

fix: stop compose from flashing in if SDK mole's moleParent doesn't exist yet

---

src/platform-implementation-js/dom-driver/gmail/widgets/gmail-mole-view-driver.ts
src/platform-implementation-js/style/gmail.css

The SDK has used reduced opacity for SDK mole title icons. This PR removes the lowered opacity in favor of Gmail's full opacity usage.
Note the slight difference in icon colors between the left (native) and right (SDK) mole.
At Streak, we use mole titleButtons in this way already downstream.

fix: mole header icons

---

examples/compose-stream/content.js

adding an example for compose view `bodyChanged` event. this helps testing if our `bodyChanged` event is emitted correctly when gmail user inserts a template. 
- turn on `Template` from gmail advanced setttings
- load example: Compose Button Stream
- open dev console
- open compose view
- insert a template
- check that dev console log `bodyChanged` event

add example for compose bodyChanged

---

gulpfile.babel.ts

https://github.com/InboxSDK/InboxSDK/pull/1047/commits/6aa392a3440b097c68ea0bf0fddd305e5331ee46 didn't account for `pageWorld.map.[hash].js` being included in part of our deploy script. This PR re-adds that output.

build: generate pageWorld source maps used by Sentry for remote deploy

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts

Some Streak user's reporting issue with buttons not being added into the thread view toolbar (via `registerThreadButton`). Looks like Gmail is rolling out a gradual update. 
log censored html of the thread view container if toolbar wasn't found or fallback to log censored page html if thread view container wasn't found.

log html if thread view toolbar was not found

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-message-view.ts

Hi **@wegry**,
I had updated the code by adding space in HTML DOM selector in the method #getOpenMoreMenu() as below 
(Tested & it is working).
I kindly request you to merge the PR ASAP as broken is feature in our extension, please let me know if you have any concerns for the same.
td > div.nH.a98.iY > div.nH .aHU .b7.J-M[aria-haspopup=true]
**@adm-bome:** Thanks for the solution.
Thanks,
Shashikiran

Fixed - Bug: messageView.addToolbarButton does not create a button #1056

---

src/platform-implementation-js/dom-driver/gmail/gmail-element-getter.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-message-view.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts

gmail started rolling out update to its thread view markup, new markup no longer contains `table.Bs` selector, PR switched to use `.a98.iY` selector (because it is present in old and new markup, it required extra condition changes etc)
the fix is tentative and may need to be tweaked further.

selectors update for gmail thread view container changes

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts
src/platform-implementation-js/lib/dom/querySelectorOrFail.ts

If the selectors neither `table.Bs > tr` or `.nH.g.id:has(.a98.iY)` are present, instead of logging a `WaitForError`, this PR alters logging to log a `SelectorError` instead. 
The latter SelectorError is easier to search for in our telemetry.

chore: more logging around #1072

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts

looks like new gmail thread container markup is not being parsed properly in split mode. Update to potential new selector, and log censored html of the preview if still cannot be found

update selector for preview pane thread container

---

.circleci/config.yml
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.prettierrc.json
README.md

This PR has two commits:
- Enable [Prettier's "proseWrap" setting](https://prettier.io/docs/en/options.html#prose-wrap) so that it does line wrapping of text and markdown files. This does affect some CI yml config files but I've verified the changes by Prettier are no-op spacing changes. I also tweaked some wording in the github issue template to look a little better with Prettier's new spacing applied.
- Fix the readme to not refer to the nonexistent "Querying for Error Logs" section which was moved into our [internal wiki](https://github.com/StreakYC/MailFoo/wiki/Developing-on-the-SDK). Also added a little basic paragraph at the start explaining the relationship of the InboxSDK to Streak since Streak is mentioned a few times in the readme.

Readme fix and formatting

---

src/common/censorHTMLstring.test.ts
src/common/censorHTMLstring.ts
src/common/extractDocumentHtmlAndCss.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts

because of gmail gradual updates there is a need in logging full document html with css so then it is possible to inspect the DOM tree and identify changes.
`extractDocumentHtmlAndCss` will output obfuscated document.body content and all css that is used on the page
example of the output

support extracting whole document html and css

---

src/platform-implementation-js/dom-driver/gmail/gmail-element-getter.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts

`.querySelector` will return the second match if it is within children of the first match, so in order to keep inboxsdk expected container, the selectors should be split

fix order of thread view parsing in split mode

---

src/inboxsdk-js/loading/platform-implementation-loader.ts
src/platform-implementation-js/main.ts

This PR prevents the SDK from loading in Gmail Compose pop out windows. We haven't supported this use case. We would be open to PRs to do so.
Related to #1062

fix: stop the SDK from starting in compose popups

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts

it appears that the Gmail search page now renders with a delay, first showing a loading spinner (and potentially more pages will be doing that soon). This broke the navigation handler that expects elements to be present instantly. Gmail adds `[role=main]` attribute once loading is finished.
the issue was reproduced on the account provided by @Alex-Chopard and @RBische thank you!

support gmail page loading state

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts

Hi, sadly we experiencing more issues with the preview pane and the detection of a selected conversation / switch to another conversation.
As I'm able to reproduce the issue on the test account, I trying a fix.
Fill free to ask if you have any question / suggestion about this PR.
Error in the console:
DOM with preview panel enabled and no conversation selected:
`.ao8` is well found but not `.a98.iY`
DOM with preview panel enabled and a conversation selected:
`.apa` has been replaced with `.a98.iY`
Without the fix:
https://github.com/InboxSDK/InboxSDK/assets/29271954/33666754-2b65-40d0-b863-8b736a854ad0
With the fix:
https://github.com/InboxSDK/InboxSDK/assets/29271954/3c2363a8-d635-4cf6-9e62-83f51d3bb3eb
#1071
Closes #1078

proposed fix for: SelectorError: Failed to find element with selector: table.Bs > tr, .ao8:has(.a98.iY)

---

src/platform-implementation-js/dom-driver/gmail/gmail-element-getter.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts

Gmail started rendering thread view asynchronously for some users, wait for thread content container element appear in the DOM before notifying with `newGmailThreadView` event

handle async thread container element

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts

`.ao9:has(.a98.iY)` selector for preview pane with opened email.
if user navigates to inbox page with preview pane enabled, opens email, navigates to another page, and then navigates back to inbox, gmail will pre open email from earlier. Having .ao8 as a thread container was preventing MutationObserver identifiying changes to the thread view dom, moving the thread container down one node (to .ao9) allows MutationObserver to identify the changes when switching between emails.

fix selector of preview pane opened thread view

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts

We have a number of selectors around ThreadViews now. This PR adds logging for which selector versions are actually in use so we can potentially simplify logic in the future.

chore(ThreadView): log selector existence

---

src/injected-js/gmail/modify-suggestions.ts

Fixes our support for modifying suggestions when no suggestions from Gmail are present. Works around a Gmail behavior change where an array we expect to be present stops being present when there are no suggestions from Gmail. This seems to restore the intended behavior.

Fix modifying suggestions when no suggestions are present

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts

Drop a few selectors around ThreadView detection. One of which, `.if`, dates back to 2014.
Logging added in #1096 seems to confirm that #1087's `el.matches('.a98.iY')` is our new ThreadView element.

chore: drop old selectors around ThreadView detection

---

gulpfile.babel.ts

If there are more than 16 files that match the patterns `./packages/core/inboxsdk.js*` `./packages/core/platform-implementation.js*` `./packages/core/pageWorld.js*`, then builds with the --remote flag fail:
```
chris@Chriss-MacBook-Air InboxSDK % yarn gulp default --remote
[22:56:42] Requiring external module @babel/register
[22:56:43] Using gulpfile ~/Coding/streak/InboxSDK/gulpfile.babel.ts
[22:56:43] Starting 'default'...
[22:56:43] Starting 'sdk'...
[22:56:43] Starting 'types'...
asset pageWorld.js 689 KiB [emitted] (name: pageWorld) 1 related asset
runtime modules 1.71 KiB 9 modules
modules by path ./node_modules/lodash/*.js 154 KiB
./node_modules/lodash/find.js 1.27 KiB [built] [code generated]
+ 205 modules
modules by path ./src/ 146 KiB 39 modules
modules by path …
```

Fix gulpfile setupExamples() step

---

src/inboxsdk.d.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-collapsible-section-view.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts
src/platform-implementation-js/driver-interfaces/route-view-driver.ts
src/platform-implementation-js/views/collapsible-section-view.ts
src/platform-implementation-js/views/route-view/list-route-view.ts
src/platform-implementation-js/views/section-view.ts

The public interface in this PR should be unchanged.
- Add doc strings to:
- `CollapsibleSectionView`
- `ListRouteView`
- remove a number of `any`s in `GmailCollapsibleSectionView`
- true private in 
- `CollapsibleSectionView`
- `GmailCollapsibleSectionView`
- `ListRouteView`
- `SectionView`
- instead of impressionistic type from `src/inboxsdk.d.ts`, export source
- `SectionView`
- `CollapsibleSectionView`
- `ListRouteView`
Move from untyped `WeakMap` membersMap in to modern private syntax:
- src/platform-implementation-js/views/collapsible-section-view.ts 
- src/platform-implementation-js/views/route-view/list-route-view.ts
- src/platform-implementation-js/views/section-view.ts

chore: prep for CollapsibleSectionView work

---

src/inboxsdk.d.ts
src/platform-implementation-js/constants/router.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-collapsible-section-view.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts
src/platform-implementation-js/driver-interfaces/route-view-driver.ts
src/platform-implementation-js/views/route-view/dummy-route-view-driver.ts
src/platform-implementation-js/views/route-view/list-route-view.ts
src/platform-implementation-js/views/route-view/route-view.ts
src/platform-implementation-js/views/section-view.ts
src/types/descriptor.d.ts

Plumb through types around `addSectionView` in `list-route-view`. `title` usage appears to be effectively optional based on our usage at Streak.

types: add SectionDescriptor to SectionView usages

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/add-button.ts
src/platform-implementation-js/driver-interfaces/compose-view-driver.ts
src/platform-implementation-js/views/compose-view.ts

Codifies existing usage of `ComposeView.prototype.addButton` upstream at [Streak](https://github.com/StreakYC/MailFoo/blob/32b9fa6882e54fe4d3e7aaf6c19c5105910d3046/extensions/common/js/modules/boxesButton/composeBoxesButton/composeBoxesButtonViewController.tsx#L248).

types: allow nullish values in kefir descriptor passed to addButton

---

src/injected-js/gmail/setup-gmail-interceptor.ts

We're seeing what might be Gmail rolling out a change to its search results format. Logging example requests and responses here will help narrow down if that's the case.

chore: add logging for suggestionsResults for streak users

---

package.json
src/common/html-to-text.ts
src/injected-js/gmail/setup-gmail-interceptor.ts
yarn.lock

Add trustedTypes with Safari fallback to account for folks starting to get https://workspaceupdates.googleblog.com/2024/01/extending-trusted-types-to-gmail.html as part of Rapid Release.
And log errors on modify suggestions instead of when a suggestions request comes back with `undefined` `modifications`.

fix: use trustedTypes and log when modifySuggestions throws an error

---

src/inboxsdk.d.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/add-button.ts
src/platform-implementation-js/views/compose-button-view.ts
src/platform-implementation-js/views/compose-view.ts

This particular bug triggers when a ComposeView.addButton is used with a descriptor. If the descriptor goes from hasDropdown === true to false, we currently trigger an empty dropdown when the button is subsequently clicked.
[Loom](https://www.loom.com/share/6a1fbcb560aa43088b3da5957bbfc149)

fix(ComposeView): clean up dropdown to prevent empty dropdown from toggling

---

examples/search-results/content.js
src/inboxsdk.d.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-collapsible-section-view.module.css
src/platform-implementation-js/dom-driver/gmail/views/gmail-collapsible-section-view.ts

It may be simpler to just update to the newer styles without configurability. We can always add classname configuration later.
<figure>
<figcaption>Note the hyphen between 'Inbox Monkeys' and 'Subtitle'. Also note the parens around 'Subtitle'.</figcaption>
</figure>

feat(SectionView): update title and subtitle support

---

package.json
src/common/html-to-text.test.ts
src/common/html-to-text.ts
src/common/removeHtmlTags.test.ts
src/common/removeHtmlTags.ts
tsconfig.json
yarn.lock

Follow-up to https://github.com/InboxSDK/InboxSDK/pull/1126. Removes dompurify which was more heavyweight and unnecessary here.
No visible behavior changes.

Make html-to-text work without dompurify

---

src/inboxsdk.d.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-collapsible-section-view.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts
src/platform-implementation-js/views/collapsible-section-view.ts
src/platform-implementation-js/views/section-view.ts

Prep for layout work around `CollapsibleSectionView`.
Runs types through events for `SectionView` and `CollapsibleSectionView`. Requires a bit of runtime rejiggering to narrow event types.
tip: ignore whitespace.

types: typed events for section views

---

examples/thread-rows/content.js
src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts
src/platform-implementation-js/views/thread-row-view.ts

Adds an onHover callback to ThreadRowView.addImage's ImageDescriptor. The callback gives an object with a `hoverEnd: Promise<void>;` property that resolves when the hover finishes.
Intended for event logging within Streak to see how often the addImage tooltip is used.
Highly recommend that for this use, only hovers that last for a certain amount of time like a second are logged in order to only see intentional hovers. This can be done like the following code examples, one using Kefir and one not:
```ts
threadRowView.addImage({
// ...
onHover(event) {
Kefir.later(1000)
.takeUntilBy(Kefir.fromPromise(event.hoverEnd))
.onValue(() => {
logHover();
});
}
});
```
```ts
threadRowView.addImage({
// ...
onHover(event) {
const timeout = setTimeout(() => {
logHover();
}, 1000); …
```

ThreadRowView.addImage onHover callback

---

src/inboxsdk.d.ts
src/platform-implementation-js/views/conversations/message-view.ts

Now that we use true private syntax in MessageView (#1157), the extra interface for TS is no longer necessary
Closes #1163

types: remove shadow interface of MessageView

---

src/platform-implementation-js/views/conversations/attachment-card-view.ts

Fixes https://github.com/InboxSDK/InboxSDK/issues/1162.
It was not possible to get the element of an AttachmentCardView except by accessing the undocumented and accidentally-exposed property `_attachmentCardImplementation._element`. This undocumented property was removed in a recent cleanup PR. This PR adds a new AttachmentCardView.getElement function and some compatibility code so that code using the old undocumented property still works (but gets a console warning recommending the new property).
Originally the InboxSDK mostly avoided adding APIs exposing Gmail elements (like `getElement()` methods) in order to encourage extensions to only inspect and modify elements through the InboxSDK so that extensions using the InboxSDK didn't do anything that didn't work in future Gmail versions or …

Add AttachmentCardView.getElement

---

src/inboxsdk.d.ts
src/platform-implementation-js/dom-driver/gmail/gmail-driver.ts
src/platform-implementation-js/dom-driver/gmail/gmail-driver/add-toolbar-button-for-app.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-app-toolbar-button-view.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-message-view.ts
src/platform-implementation-js/namespaces/compose.ts
src/platform-implementation-js/namespaces/toolbars.ts

Fixes https://github.com/InboxSDK/InboxSDK/issues/1158, https://github.com/InboxSDK/InboxSDK/issues/1159, https://github.com/InboxSDK/InboxSDK/issues/1161
Only one behavior change: an error caused by accessing a private property on the wrong `this` value is fixed in the getter of the long-deprecated `LegacyListToolbarButtonDescriptor.threadRowViews` property.

Misc type definition fixes

---

src/inboxsdk.d.ts
src/platform-implementation-js/lib/handler-registry.ts
src/platform-implementation-js/namespaces/router.ts

This type was a remnant from when we had three parallel type definitions: Flow, our external typescript interface, and our internal typescript interface.
Addresses @amiram's [comment](https://github.com/InboxSDK/InboxSDK/issues/1161#issuecomment-2038953192).

types: Remove shadow RouteView type

---

src/inboxsdk.d.ts

db0697ce8fc715a3596a931e45c61ed0af2225a9 improved typing. Downstream in Streak, we need the unexported type reexported here

types: reexport LegacyToolbarButtonOnClickEvent

---

src/inboxsdk.d.ts
src/platform-implementation-js/views/conversations/thread-view.ts

Removes impressionistic type from long ago when our TS definitions were separate between source and the interface. Simplifies type addition in #1128.

types: remove shadow type of ThreadView

---

packages/core/background.js

I've figured out that sometimes when opening a new Gmail tab, Chrome preloads Gmail including extension content scripts before Gmail is shown, but the InboxSDK fails to initialize in this case because the extension service worker fails to inject the page-world script because the tab is still at the Chrome new tab and not Gmail. (The InboxSDK would initialize correctly if the user refreshes in the new tab.) Specifying the frame id to inject the page-world script into fixes this.

Fix InboxSDK loading in preloaded page in MV3 extension

---

gulpfile.babel.ts
package.json
yarn.lock

1. It seems like we forgot to enable sourcemaps on our production npm build. (If args.production was on, we wouldn't make source maps, and if it was off, we'd make inline source maps. I've just made it always use external source maps now. I think I might have previously configured some things to use inline source maps in dev because I wasn't sure how to make external source map files work in an MV3 extension, but I've since figured out they work fine if you list them in the manifest's web_accessible_resources, as I've updated the [hello-world example extension](https://github.com/InboxSDK/hello-world) to.) (The "integrated page world" build still uses inline source maps because the workflow it was built for involved copying the inboxsdk.js file alone around. I think that build won't be …

Fix npm build source maps

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts

Tweak the notice bar bottom spacing when AI suggestions ("Summarize this email" etc.) are enabled in the thread view. 
Example:
| Before the fix      | After the fix |
| ----------- | ----------- |
| ![image](https://github.com/InboxSDK/InboxSDK/assets/108280206/5c4f5e1b-e4dc-461c-9926-28eed2c5b99f)  | ![image](https://github.com/InboxSDK/InboxSDK/assets/108280206/b75072d2-f971-4f4d-9950-0b9ec42af120) |

fix(thread view): tweak notice bar spacing with ai suggestions container

---

README.md
src/platform-implementation-js/dom-driver/gmail/views/gmail-nav-item-view.ts

closes https://github.com/InboxSDK/InboxSDK/issues/1168; have updated the docs accordingly in https://github.com/InboxSDK/inboxsdk-docs/pull/29
also added clarifications to the README to make it easier for newcomers to set things up
have also opened [a further PR](https://github.com/zxt-tzx/InboxSDK/pull/1) based on top of this to refactor the `/example/app-menu`, happy to include that within this PR instead

fix: DropdownButtonAccessoryDescriptor.onClick type

---

examples/sidebar-example/content.js
src/platform-implementation-js/dom-driver/gmail/views/gmail-app-sidebar-view/primary/index.module.css
src/platform-implementation-js/dom-driver/gmail/views/gmail-app-sidebar-view/primary/index.tsx
src/platform-implementation-js/driver-common/sidebar/AppSidebar.tsx
src/platform-implementation-js/driver-common/sidebar/ContentPanelViewDriver.ts

In `AppSidebar`, allow the same sort of `iconLiga` setup that was added in #1174.
The third icon down in both screenshots uses the new option. The extension I tested with was `sidebar-example`.

feat: add iconLiga option for right sidebar

---

examples/build.ts

When building with `yarn start`, we had an issue after #1188 where in `yarn start` builds: 
1. `esbuild.rebuild` was signaling completion
2. We started copying `examples/dist` into each example extension
3. A `rebuild.watch` started up and cleared `examples/dist`.
4. `background.js` wasn't ending up in `examples/compose-stream/` on the first build.
This issue didn't seem to occur on subsequent rebuilds.
This PR removes the build and then copy that was causing issues. One ESBuild context is used instead of separate configs for service worker output and content scripts.

fix: prevent race condition in `yarn start` around `background.js`

---

package.json
src/injected-js/setupCustomViewEventAssassin.ts
src/injected-js/setupInboxCustomViewLinkFixer.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.ts
src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/page-parser.ts
yarn.lock

- Removed closest imports
- Removed the first param and leave the classname as the only one
Closes https://github.com/InboxSDK/InboxSDK/issues/1190

chore: Drop closest-ng library

---

src/common/get-extension-id.ts

In Chrome MV3 extensions, `chrome.extension.getURL()` has been changed to `chrome.runtime.getURL()`. This PR updates our code so we can use the correct function when present in order to get the extension id in error logs.

Fix reading extension id for error logging in MV3

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-attachment-card-view.ts

Fixes https://github.com/InboxSDK/InboxSDK/issues/1204.
The AttachmentCardView.getDownloadURL() method started failing recently on html attachments, possibly because of a recent Gmail change. The "download_url" attribute set by Gmail that the InboxSDK reads has a string separated with colons and a URL. The URL now contains colons sometimes, and the regex we would use to get the URL out of the "download_url" attribute would not handle that correctly.

Fix AttachmentCardView.getDownloadURL() on html attachments

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-app-menu-item-view.ts
src/platform-implementation-js/namespaces/app-menu.ts
src/platform-implementation-js/views/app-menu-item-view.ts
src/platform-implementation-js/views/collapsible-panel-view.ts

Gmail could set app menu item to active asynchronously, monitor changes to the menu DOM and deactivate all other menu items that don't have the SDK specific active class name.
Same applies to menu panel. Deactivate all other panels that don't have the SDK specific active class name.

app menu: handle async activation

---

src/common/get-extension-id.ts

When an extension is reloaded or removed, certain Chrome APIs in its content scripts switch to throwing "Extension context invalidated" errors when called. The InboxSDK is mostly unaffected since it mostly doesn't use these APIs, except when logging an error it tries to get the extension's ID using a Chrome API. This means that the next time the InboxSDK tries to log an error after the extension is reloaded or removed, the InboxSDK ends up interrupting itself with a new error from trying to look up the extension ID. (This doesn't cause an infinite loop because we catch any errors thrown while logging an error and log them through a simpler code path, but it does add a lot of noise in the console that distracts from any actual errors triggered by the extension itself.)
This PR fixes this …

Cache extension ID, avoid "Extension context invalidated" errors in logs

---

packages/core/background.js
src/injected-js/main.ts

This PR prevents the issue described in https://github.com/w3c/webextensions/issues/8 from affecting the execution of pageWorld.js. I've never observed the issue happening, though I expect that if it did then it would cause some confusing console errors. I avoid the issue by using the [`documentIds` option to scripting.executeScript()](https://developer.chrome.com/docs/extensions/reference/api/scripting#type-InjectionTarget) when available (Chrome 106+) and otherwise by checking within the injected script that it's running in the document that requested it.

Prevent pageWorld.js from possibly running in the wrong page

---

src/common/log-error.ts

The console logging we do when we catch an uncaught error is a bit redundant, and on Safari the redundant parts are useless because the stack property of errors in content scripts don't have file and line number information. Also the formatting of parts of the logged text is bad on Safari specifically. This PR removes the redundant parts of what we log to the console and also improves the formatting of the rest to look better in Safari.
1. When we log an error to the console, we logged the error, the error's stacktrace, and the stacktrace of the current logging call. It's redundant to log the error's stacktrace because it can be viewed by expanding the error in the console. It's redundant to log the stacktrace of the current logging call because the browser already shows the stacktrace on …

Better simpler console error logging

---

examples/build.ts
gulpfile.babel.ts
package.json

- Building InboxSDK examples with the --watch flag would start esbuild again every time any input file was changed.
- Re-enable building the examples by default with the InboxSDK.

Fix build InboxSDK examples with --watch flag

---

examples/nav-menu/content.js
src/platform-implementation-js/dom-driver/gmail/views/gmail-nav-item-view.ts

This PR fixes two issues:
- If Gmail is set so both Chat and Meet are disabled, and a stream passed to `NavMenu.addNavItem()` emits a value with a accessory button multiple times, then the accessory button would disappear from the page.
- If Gmail is set so Chat is on, and a stream passed to `NavMenu.addNavItem()` emits its first value after child nav items have been added, then the value's name property would be set on a child of the nav item instead of directly on the nav item.

Fix nav item name and plus ("create") button not showing up always

---

examples/add-route-view-sections/content.js
src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts
src/platform-implementation-js/driver-interfaces/route-view-driver.ts
src/platform-implementation-js/style/gmail.css
src/platform-implementation-js/views/route-view/list-route-view.ts

Adds ListRouteView hideSearchPageFilterToolbar() method that hides this top toolbar on search pages:
Currently does nothing on non-search pages (such as Sent) even though some other pages have a visually similar filter toolbar, as those toolbars are structured differently in the document.

Add ListRouteView.hideSearchPageFilterToolbar() method

---

src/platform-implementation-js/style/gmail.css

Gmail has new popover styles for editing links. Fix the positioning of the SDK popovers.
A tad suspicious why I had the top position defined in the first place but maybe there was something going on with that container that they changed to support the new content state (there are still states that use the old style popover)
Before:
After:

Tweak positioning to work with both old and new popover style

---

src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/setupLinkPopovers.ts
src/platform-implementation-js/views/compose-view.ts

Two functions to help users access contents of gmail's link popover easier. This is helpful with gmail's new UI where the link editing happens in the popover rather than a separate modal, so there are more states and more activity in the popover now.

additional getters in linkPopOver

---

src/platform-implementation-js/views/conversations/message-view.ts

@Macil same motivation and reasoning as https://github.com/InboxSDK/InboxSDK/pull/1165:
Gmail has been relatively stable, Google Inbox was discontinued, it's extremely useful to prototype features using direct access to elements outside of the InboxSDK, and some extensions want to do things that the InboxSDK doesn't want to commit to maintaining, so we're much more willing to expose Gmail elements now where it's useful to.

add MessageView.getElement

---

src/platform-implementation-js/dom-driver/gmail/gmail-driver/show-custom-thread-list.ts

This is a potential fix for issue [#1155](https://github.com/InboxSDK/InboxSDK/issues/1155#top). 
My findings are in the comments of the above issue. 
Tests were unaffected by the change 🤔.
- Create a mutationObserver stream on the input box that listens for changes in "role" before setting the visibility of the input box to `visible` (a little brittle I know). This attribute change happens right after the `input.value` is set.
- Remove `nextMainContentElementChange.onValue` to set the the visibility of the input box to `visible`

Potential fix for issue #1155.

---

src/platform-implementation-js/dom-driver/gmail/widgets/gmail-mole-view-driver.ts

when google chat and meet are disabled, the moleParent element has no children initially, unlike when enabled and there is a hidden mole like stub created by gmail

fix gmail mole

---

src/platform-implementation-js/style/gmail.css

looks like we no longer need the sidebar width override now.
close https://github.com/InboxSDK/InboxSDK/issues/1258
before fix:
https://www.loom.com/share/180105b1fd0846e4b2342989b7fbe6a3
after fix:
https://www.loom.com/share/80aac8d3ede949e9aae4cba66b2a6396

remove mole position overrides

---

examples/sidebar-example/content.js
src/platform-implementation-js/dom-driver/gmail/gmail-driver/show-app-id-warning.ts
src/platform-implementation-js/driver-common/sidebar/ContentPanelViewDriver.ts

When I tried call `remove` on a `ContentPanelView`, the method would error out with a message reading `should not happen: failed to find orderItem`. The given content panel would also not be removed and the interior contents were left in an unusable state.
* The underlying issue proved to be that the `inboxsdkRemoveSidebarPanel` was missing the `isGlobal` property from its event `detail` property.
* In GmailAppSidebarView, the `isGlobal` property is used to determine whether a given event is coming from a "thread sidebar" or a "global sidebar" (see `GmailAppSidebarPrimary::844` and `GmailAppSidebarPrimary::1006`).
* Because the `inboxsdkRemoveSidebarPanel` event was missing the `isGlobal` property, the `isGlobal` check would resolve as `false` and the event was ingested by the "thread …

Sidebar removal fix
