InboxSDK/InboxSDK

- packages/core/inboxsdk.d.ts
- src/platform-implementation-js/dom-driver/gmail/widgets/gmail-label-view.js
Allows passing an HTML along with text for thread row labels.
> feat(labels): allow thread row label title customization

- src/platform-implementation-js/lib/logger.ts
> fix: TypeError in logging inboxSDKinjectedError events

- gulpfile.babel.ts
- package.json
- src/types/gulp-add-src.d.ts
- src/types/gulp-terser.d.ts
- yarn.lock
Swap ES2018 compatible minifier terser in for uglify.
> Fix: use modern syntax capable minifier

- examples/app-menu/content.js
- src/platform-implementation-js/dom-driver/gmail/gmail-driver/add-collapsible-panel.ts
- src/platform-implementation-js/namespaces/app-menu.ts
- src/platform-implementation-js/style/gmail.css
- src/platform-implementation-js/views/collapsible-panel-view.ts
Add placeholder for loading into experimental collapsible panels.
> feat: loading-icon-support

- src/platform-implementation-js/dom-driver/gmail/gmail-driver/add-app-menu-item.ts
- src/platform-implementation-js/dom-driver/gmail/gmail-driver/add-collapsible-panel.ts
- src/platform-implementation-js/views/app-menu-item-view.ts
- src/platform-implementation-js/views/collapsible-panel-view.ts
Update the styling (color) and positioning of the collapsible panel nubs
> fix(app menu): panel nub positioning

- examples/custom-view/content.js
- src/platform-implementation-js/dom-driver/gmail/views/gmail-nav-item-view.ts
Add the same tooltip as Gmail use for his labels.
> Feature Request: Add tooltip to NavItemViews

- src/platform-implementation-js/dom-driver/gmail/gmail-driver/show-custom-thread-list.ts
- src/platform-implementation-js/dom-driver/gmail/gmail-sync-response-processor.ts
> Fix gmail response changes

- examples/thread-rows/content.js
- src/inboxsdk.d.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.js
- src/platform-implementation-js/driver-interfaces/thread-row-view-driver.js
- src/platform-implementation-js/views/thread-row-view.js
Updated example extension `Thread Rows`
> Add replaceSubject to thread row view

- .eslintrc.js
- src/injected-js/gmail/setup-gmail-interceptor.js
- src/injected-js/xhr-proxy-factory.js
- src/platform-implementation-js/dom-driver/gmail/gmail-driver/getSyncThreadFromSyncThreadId.js
- src/platform-implementation-js/dom-driver/gmail/gmail-driver/setup-route-view-driver-stream.ts
- src/platform-implementation-js/dom-driver/gmail/gmail-driver/thread-row-identifier.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-attachment-area-view.js
- src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.js
- src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/add-compose-notice.js
- src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/from-manager.js
- src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/get-formatting-area-offset-left.js
- src/platform-implementation-js/dom-driver/gmail/views/gmail-message-view.js
- src/platform-implementation-js/dom-driver/gmail/views/gmail-message-view/get-updated-contact.js
- src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.js
- src/platform-implementation-js/dom-driver/gmail/widgets/gmail-tooltip-view.js
- src/platform-implementation-js/driver-common/sidebar/AppSidebar.js
- src/platform-implementation-js/namespaces/keyboard.js
- Moves over straggler `class` wrapped `ud.defn` usage missed in #910
- turns on ESLint's `prefer-const` for flow files ahead of #913
> chore: reduce noise before #913

- src/platform-implementation-js/namespaces/app-menu.ts
- src/platform-implementation-js/views/app-menu-item-view.ts
- src/platform-implementation-js/views/collapsible-panel-view.ts
We've had the AppMenu in use at Streak for 3+ months now. We believe that the AppMenu is stabilized. This PR tweaks a bit of TSDoc to reflect that.
> docs: officially release AppMenu

- examples/app-menu/content.js
- examples/compose-tooltip-button/content.js
- examples/types.d.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/add-button.ts
Work around looking into #801.
Includes:
- Type work to see how `ComposeView` and its corresponding driver interact
- Types in examples
> chore: ComposeView implements ComposeViewDriver

- src/platform-implementation-js/namespaces/global.ts
https://github.com/InboxSDK/InboxSDK/issues/950#issuecomment-1647824978
> types: plumb through Driver type associated with source map trace in

- .eslintignore
- package.json
- src/platform-implementation-js/dom-driver/gmail/views/gmail-app-sidebar-view/index.test.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-app-sidebar-view/primary/index.tsx
- src/platform-implementation-js/dom-driver/gmail/views/gmail-attachment-card-view.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts
Match flags added in https://github.com/StreakYC/MailFoo/commit/7ee3e4b4795332cd7ea752c49e79ccf811f0dd00
> chore: match ESLint flags around max-warnings in downstream repo

- __tests__/injected-thread-identifier.ts
- __tests__/repo.js
- src/platform-implementation-js/dom-driver/gmail/views/gmail-app-sidebar-view/index.test.ts
- tools/deserialize.js
- tools/serialize.js
Remove some noise from #969 tests breaking.
> chore: patch up test failing locally

- gulpfile.babel.ts
- src/inboxsdk-js/loading/platform-implementation-loader.ts
This reverts commit 958d1cde12a2e2552c41a20f0de7e7044df2dd57.
> Revert "chore: append sourceURL in lieu of sourceMappingURL"

- src/inboxsdk.d.ts
- src/platform-implementation-js/constants/toolbars.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts
- src/platform-implementation-js/namespaces/toolbars.ts
- src/platform-implementation-js/views/app-toolbar-button-view.ts
- src/platform-implementation-js/views/conversations/thread-view.ts
Cherry pick a few type only commits from #976.
> chore: more types around #939

- src/inboxsdk.d.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/get-body-changes-stream.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/get-response-type-changes-stream.ts
- src/platform-implementation-js/driver-common/compose/getDiscardStream.ts
- src/platform-implementation-js/driver-common/compose/getPresendingStream.ts
- src/platform-implementation-js/driver-interfaces/compose-view-driver.ts
- src/platform-implementation-js/views/compose-view.ts
Hoist type changes from #961 by cherry picking ce34c9e7bdda1139b6f664c473456d743f984879.
> types: TypedEmitter and event stream for ComposeView and Driver

- package.json
- yarn.lock
`brfs` hasn't been hooked up since #881
> chore: drop brfs

- src/platform-implementation-js/dom-driver/gmail/gmail-driver/gmail-load-event.ts
- src/platform-implementation-js/dom-driver/gmail/gmail-driver/track-gmail-styles.ts
- src/platform-implementation-js/lib/wait-for.ts
> fix: wait for nav item before checking isDarkMode in gmailLoadEvent

- src/platform-implementation-js/dom-driver/gmail/gmail-driver.ts
- src/platform-implementation-js/dom-driver/gmail/gmail-driver/add-nav-item.ts
- src/platform-implementation-js/dom-driver/gmail/gmail-driver/isIntegratedViewGmail.ts
- src/platform-implementation-js/dom-driver/gmail/gmail-element-getter.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-nav-item-view.ts
- src/platform-implementation-js/namespaces/nav-menu.ts
- src/platform-implementation-js/views/native-nav-item-view.ts
> types: connect legacy NavMenu namespace down to shouldAddNavItemsInline

- __tests__/inboxsdk-gmail.ts
- src/inboxsdk-js/inboxsdk-NONREMOTE.ts
- src/inboxsdk-js/inboxsdk-REMOTE.ts
- src/inboxsdk-js/inboxsdk-TEST.ts
- src/inboxsdk-js/inboxsdk.ts
- src/inboxsdk-js/loading/load-platform-implementation-NONREMOTE.ts
- src/inboxsdk-js/loading/platform-implementation-loader.ts
- src/platform-implementation-js/main.ts
Uses the SDK's local Deferred and Promises to bootstrap the NONREMOTE SDK.
> Use deferred and promises to bootstrap the NONREMOTE SDK

- src/platform-implementation-js/dom-driver/gmail/gmail-driver.ts
- src/platform-implementation-js/dom-driver/gmail/gmail-driver/gmail-load-event.ts
- src/platform-implementation-js/dom-driver/gmail/gmail-driver/isIntegratedViewGmail.ts
- src/platform-implementation-js/lib/logger.ts
Adds
- `isSidePanelCollapsed`
- `isGoogleChatEnabled`
https://www.loom.com/share/8c5c8322f4614f3f9b9a288de521d373
> chore: more load event data

- src/platform-implementation-js/dom-driver/gmail/gmail-element-getter.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/page-parser.ts
- close https://github.com/InboxSDK/InboxSDK/issues/1042 -> tested example: thread-row
- close https://github.com/InboxSDK/InboxSDK/issues/1041 -> tested example: thread-test
- also fix an issue where we can't find section container causing collapsible section not attached. -> tested example: search-results
> Fix gmail route view setup 

- src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts
fix invalid notice bar selector added in https://github.com/InboxSDK/InboxSDK/pull/1073
> fix notice bar selector

- packages/core/package.json
- src/platform-implementation-js/dom-driver/gmail/gmail-driver.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts
Improves typing in Driver around Toolbars, RouteView, and ThreadView.
> types: ThreadView and RowListView in Driver

- .eslintignore
- src/platform-implementation-js/namespaces/butter-bar.ts
- src/platform-implementation-js/namespaces/compose.ts
- src/platform-implementation-js/namespaces/conversations.ts
- src/platform-implementation-js/namespaces/keyboard.ts
- src/platform-implementation-js/namespaces/lists.ts
- src/platform-implementation-js/namespaces/router.ts
- src/platform-implementation-js/views/app-toolbar-button-view.ts
- src/platform-implementation-js/views/collapsible-section-view.ts
- src/platform-implementation-js/views/conversations/attachment-card-view.ts
- src/platform-implementation-js/views/keyboard-shortcut-handle.ts
- src/platform-implementation-js/views/nav-item-view.ts
- src/platform-implementation-js/views/route-view/custom-route-view.ts
- src/platform-implementation-js/views/route-view/list-route-view.ts
- src/platform-implementation-js/views/route-view/route-view.ts
- src/platform-implementation-js/views/section-view.ts
- src/platform-implementation-js/widgets/buttons/dropdown-view.ts
- src/platform-implementation-js/widgets/drawer-view.ts
- src/platform-implementation-js/widgets/modal-view.ts
Remove comment about src/docs. We haven't had a src/docs folder since this project was open sourced.
> chore: drop vestigial doc comment

- examples/search-results/content.js
- src/platform-implementation-js/dom-driver/gmail/views/gmail-collapsible-section-view.ts
- src/platform-implementation-js/style/gmail.css
https://www.loom.com/share/f2ada147cd794f4f9d4ce25f74c7129a
> fix: dropdown flashing in collapsible section view

- yarn.lock
> Bump `caniuse-lite`

- package.json
- yarn.lock
Necessary for a narrowing bug in tsc with #1140.
> bump typescript

- src/platform-implementation-js/dom-driver/gmail/gmail-driver.ts
- src/platform-implementation-js/dom-driver/gmail/gmail-driver/track-gmail-styles.ts
- src/platform-implementation-js/dom-driver/gmail/gmail-element-getter.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-collapsible-section-view.module.css
- src/platform-implementation-js/dom-driver/gmail/views/gmail-collapsible-section-view.ts
- src/platform-implementation-js/namespaces/global.ts
Distinguish between dark themes being the frame and body, or just the frame.
https://www.loom.com/share/00f7571f11e0458b9aa15b11a344931b
Closes #1143.
> feat: more granular gmail dark theme detection

- src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-row-view.ts
Increase type coverage in GmailThreadRowView. There should be no behavior changes or externally visible type changes in this PR.
(A little work first done in https://github.com/InboxSDK/InboxSDK/pull/1147 that still seems useful)
> More type coverage in GmailThreadRowView

- src/inboxsdk.d.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-collapsible-section-view.ts
- src/platform-implementation-js/dom-driver/gmail/views/gmail-route-view/gmail-route-view.ts
- src/platform-implementation-js/views/collapsible-section-view.ts
- src/platform-implementation-js/views/section-view.ts
Recreate #1140 with main as the target branch.
> types(*SectionView): typed events

- src/platform-implementation-js/dom-driver/gmail/gmail-driver/show-custom-thread-list.ts
> Filter duplicate IDs to ensure custom lists with attachments will always render

- src/inboxsdk.d.ts
Fixes https://github.com/InboxSDK/InboxSDK/issues/1160
> Fix MessageAttachmentIconDescriptor types

- src/inboxsdk.d.ts
- src/platform-implementation-js/dom-driver/gmail/widgets/buttons/button-view.ts
Allow users to specify a default ButtonView.innerText for use with iconClass and icon fonts
> chore(ButtonView): add iconLiga

- __tests__/inboxsdk-gmail.ts
- examples/compose-dropdown-button/content.js
- examples/modal-example/content.js
- examples/override-edit-subject/content.js
- examples/toolbar-button/content.js
- src/inboxsdk-js/inboxsdk.ts
- src/inboxsdk-js/loading/platform-implementation-loader.ts
- src/inboxsdk.d.ts
- src/platform-implementation-js/lib/logger.ts
- src/platform-implementation-js/main.ts
- src/platform-implementation-js/namespaces/global.ts
- src/platform-implementation-js/namespaces/modal.ts
- src/platform-implementation-js/platform-implementation.ts
- Remove dead `inboxBeta` option that was tied to #887.
- Expose `PiOpt` type and run through usages in `Modal`, `Logger`, and `Global`
> chore(platform-implementation): drop inboxBeta opt

- src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts
Change the selector so that it accepts the inline compose or the button version of the bottom element, and then can set the observer up more properly
> tweak selector for last message footer button adding

- src/platform-implementation-js/dom-driver/gmail/views/gmail-thread-view.ts
*** might not actually be the issue don't do anything with this for the moment ***
> broaden selector and add additional logging for bottom button

- .prettierignore
- README.md
- examples/app-menu/content.ts
satcking this PR as described https://github.com/InboxSDK/InboxSDK/pull/1186#issue-2267303829
> refactor: app-menu/content.ts example for easier local dev

- src/platform-implementation-js/dom-driver/gmail/views/gmail-compose-view/setupLinkPopovers.ts
- src/platform-implementation-js/style/gmail.css
- src/platform-implementation-js/views/compose-view.ts
Actually this one would be helpful too. Same reasoning/thing as https://github.com/InboxSDK/InboxSDK/pull/1239 
Also a little tweak to the width in the new gmail UI case.
> Add getter for link popover text input
